return {
  version = "1.10",
  luaversion = "5.1",
  tiledversion = "1.10.2",
  class = "",
  orientation = "orthogonal",
  renderorder = "right-down",
  width = 10,
  height = 7,
  tilewidth = 16,
  tileheight = 16,
  nextlayerid = 12,
  nextobjectid = 133,
  properties = {},
  tilesets = {
    {
      name = "basictiles",
      firstgid = 1,
      filename = "basictiles.tsx"
    },
    {
      name = "things",
      firstgid = 121,
      filename = "things.tsx",
      exportfilename = "things.lua"
    }
  },
  layers = {
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 10,
      height = 7,
      id = 1,
      name = "Floor",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        1, 1, 1, 1, 1, 1, 1, 18, 1, 1,
        1, 18, 1, 74, 1, 74, 74, 18, 74, 1,
        1, 74, 74, 74, 1, 74, 74, 74, 74, 1,
        1, 74, 74, 74, 1, 74, 74, 74, 74, 1,
        1, 1, 18, 1, 1, 74, 74, 74, 74, 1,
        1, 74, 74, 74, 74, 74, 74, 74, 74, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 10,
      height = 7,
      id = 2,
      name = "Animations",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 193, 0, 193, 0, 0, 193, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "tilelayer",
      x = 0,
      y = 0,
      width = 10,
      height = 7,
      id = 5,
      name = "Objects",
      class = "",
      visible = true,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      encoding = "lua",
      data = {
        0, 68, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 2147483705, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 68, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 6,
      name = "Game Walls",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 1,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 0,
          y = 68,
          width = 16,
          height = 44,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 2,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 144,
          y = 16,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 10,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 64,
          y = 0,
          width = 44,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 12,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 16,
          y = 96,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 14,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 132,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 32,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 84,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 44,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 52,
          y = 16,
          width = 8,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 46,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 52,
          y = 65,
          width = 12,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 47,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 64,
          y = 16,
          width = 16,
          height = 60,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 49,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 47,
          width = 14,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 50,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 36,
          width = 3,
          height = 7,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 51,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 4,
          height = 20,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 61,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 28,
          y = 68,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 62,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 108,
          y = 0,
          width = 4,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 63,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 128,
          y = 0,
          width = 4,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 64,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 132,
          y = 0,
          width = 28,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 67,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 48,
          y = 68,
          width = 4,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 68,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 0,
          y = 16,
          width = 15,
          height = 52,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 69,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 64,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 70,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 46,
          width = 12,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 71,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 45,
          width = 10,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 72,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 44,
          width = 8,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 73,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 32,
          y = 43,
          width = 6,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 82,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 41,
          y = 24,
          width = 14,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 83,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 43,
          y = 25,
          width = 12,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 84,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 45,
          y = 26,
          width = 10,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 85,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 47,
          y = 27,
          width = 8,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 86,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 49,
          y = 28,
          width = 6,
          height = 1,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 132,
          name = "",
          type = "wall",
          shape = "rectangle",
          x = 16,
          y = 65,
          width = 12,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 3,
      name = "Draw",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 31,
          name = "lockingDoor 2",
          type = "draw",
          shape = "rectangle",
          x = 32,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 59,
          name = "lockingDoor 1",
          type = "draw",
          shape = "rectangle",
          x = 112,
          y = 0,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 8,
      name = "Collision Regions",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 15,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 0,
          y = 64,
          width = 16,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 16,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 144,
          y = 16,
          width = 16,
          height = 96,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 17,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 32,
          y = 0,
          width = 76,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 18,
          name = "torch",
          type = "detect",
          shape = "rectangle",
          x = 52,
          y = 16,
          width = 8,
          height = 14,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 23,
          name = "lockingDoor 2",
          type = "detect",
          shape = "rectangle",
          x = 28,
          y = 64,
          width = 24,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 24,
          name = "Room 3 teleport",
          type = "detect",
          shape = "rectangle",
          x = 112,
          y = -4,
          width = 16,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 33,
          name = "torch",
          type = "detect",
          shape = "rectangle",
          x = 132,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 34,
          name = "Room 7 teleport",
          type = "detect",
          shape = "rectangle",
          x = 35,
          y = 32,
          width = 1,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 42,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 132,
          y = 0,
          width = 28,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 43,
          name = "text 1",
          type = "detect",
          shape = "rectangle",
          x = 52,
          y = 64,
          width = 16,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 52,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 16,
          y = 64,
          width = 12,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 53,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 68,
          y = 16,
          width = 12,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 54,
          name = "torch",
          type = "detect",
          shape = "rectangle",
          x = 84,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 55,
          name = "torch",
          type = "detect",
          shape = "rectangle",
          x = 132,
          y = 16,
          width = 8,
          height = 8,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 56,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 16,
          y = 96,
          width = 128,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 58,
          name = "lockingDoor 1",
          type = "detect",
          shape = "rectangle",
          x = 108,
          y = 0,
          width = 24,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 66,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 64,
          y = 16,
          width = 4,
          height = 48,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 78,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 32,
          y = 16,
          width = 3,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 79,
          name = "stairs",
          type = "detect",
          shape = "rectangle",
          x = 32,
          y = 43,
          width = 14,
          height = 5,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 80,
          name = "stairs",
          type = "detect",
          shape = "rectangle",
          x = 32,
          y = 32,
          width = 3,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 81,
          name = "stairs",
          type = "detect",
          shape = "rectangle",
          x = 36,
          y = 32,
          width = 10,
          height = 11,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 130,
          name = "wall",
          type = "detect",
          shape = "rectangle",
          x = 0,
          y = 0,
          width = 12,
          height = 64,
          rotation = 0,
          visible = true,
          properties = {}
        },
        {
          id = 131,
          name = "text 2",
          type = "detect",
          shape = "rectangle",
          x = 12,
          y = 0,
          width = 20,
          height = 16,
          rotation = 0,
          visible = true,
          properties = {}
        }
      }
    },
    {
      type = "objectgroup",
      draworder = "topdown",
      id = 9,
      name = "Moving Walls",
      class = "",
      visible = false,
      opacity = 1,
      offsetx = 0,
      offsety = 0,
      parallaxx = 1,
      parallaxy = 1,
      properties = {},
      objects = {
        {
          id = 29,
          name = "lockingDoor 1",
          type = "movingWall",
          shape = "rectangle",
          x = 112,
          y = 0,
          width = 16,
          height = 12,
          rotation = 0,
          visible = true,
          properties = {
            ["Door-open"] = false
          }
        },
        {
          id = 60,
          name = "lockingDoor 2",
          type = "movingWall",
          shape = "rectangle",
          x = 32,
          y = 68,
          width = 16,
          height = 4,
          rotation = 0,
          visible = true,
          properties = {
            ["Door-open"] = false
          }
        }
      }
    }
  }
}
